### ISSUE TITLE
use `mac` or `osx` instead of `darwin` as a bundle name in the release page

### ISSUE THREAD

**Issue by denkigai** [tanksuzuki/easel#19]
appreciate your great work!

it's hard to grasp immediately which one is the DL file for Mac OSX for newbies like me with your way of naming the files.  you should use `mac` or `osx` as a prefix. keep on your great work.

**Comment by tanksuzuki** [comment]
I agree with you. 👍 
I will change the bundle name and add homebrew to the installation method.
